### PR TITLE
Build region list in domain files

### PR DESCRIPTION
**Pull request by SlayterDev**
Tag domain files with the region if found in the config.

**How it works**

* Tracker-Radar-Collector has been updated to write the proxy host used to the `metadata.json` file
* In `config.json` we'll add a map under the `flags` section that has `proxyHost -> region (2 letter country code)`
* ~The detector will look in the tracker-radar for existing domain files and copy the region array (if exists)~
* The detector will write the domain files to a new region specific directory determined by the region map.
* Tag the domain with the region in _this_ crawl (US is assumed when the proxy is missing) by appending the country code to the source property

### CODE REVIEW

**Comment by SlayterDev** [comment]
@kdzwinel @jdorweiler see the updated description of this PR

**Comment by jdorweiler** [comment]
Don't forget the generated files https://github.com/duckduckgo/tracker-radar/tree/master/build-data/generated

**Comment by SlayterDev** [comment]
> Don't forget the generated files https://github.com/duckduckgo/tracker-radar/tree/master/build-data/generated

Most of the generated files apply to entities which aren't being affected by this change. I see `releasestats.txt` being generated with the trackers. Should that be the one file sorted into region directories?

**Comment by jdorweiler** [comment]
Looks good, thanks. We can just do releasestats.txt for now. The others are going to be more complicated to do regional versions of.

**Pull request merged**
